name: GenerateSnake
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-repository:
    name: Update this repo's README with repository_owner
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PROFILE_TOKEN }}
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./snake/snake.svg
            ./snake/snake-dark.svg?palette=github-dark
      - name: Fetch
        run: git fetch --all
      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./snake/snake.svg ./snake/snake-dark.svg
          git commit -m ":rocket: Update README with new snake SVGs"
          git push
